### ISSUE TITLE
Suggestion: tell users where the file is saved

### ISSUE THREAD

**Issue by cassidyjames** [ryonakano/reco#10]
I see that the app saves out to ~/Recordings, but it would be helpful to tell that to the user, perhaps with a button to open the recording location after finishing a recording.

**Comment by ryonakano** [comment]
![screenshot from 2018-12-08 20-14-31](https://user-images.githubusercontent.com/26003928/49685396-fc4bfc00-fb25-11e8-96bd-227c27ddda58.png)

@cassidyjames Thank you for your suggestion, now the app shows a notification when finishes recording, and users can open the location of files by clicking that notification.

**Comment by harisvsulaiman** [comment]
The notification doesn't always show.

**Comment by ryonakano** [comment]
@harisvsulaiman Hello, could you describe your situation? Did you installed the app from AppCenter or by building? When do you see notifications and when don't you see?

**Comment by ryonakano** [comment]
@harisvsulaiman Now Reco 1.0.0 which comes with this feature is available on AppCenter, so I think you should see notification after recording. If not, please create a new issue.
