### ISSUE TITLE
Arch Linux Support

### ISSUE THREAD

**Issue by btd1337** [ryonakano/reco#11]
I will support your application in Arch Linux. Please, consider to use 2 branchs: master (stable code), develop (development code).

Please add a section containing the following instruction:

## Arch Linux
Arch Linux users can find `Reco` under the name [reco-git](https://aur.archlinux.org/packages/reco-git/) in the **AUR**:

`$ aurman -S reco-git`

**Comment by ryonakano** [comment]
@btd1337 Thank you! I've added installation instruction for Arch Linux in 7e71d9f89db64d49d379e7823c1c25ec6ffb0647
