### ISSUE TITLE
Tell the finishing of recording and destination in a way other than system notifications

### ISSUE THREAD

**Issue by HansCronau** [ryonakano/reco#14]
Thanks for making Reco!

I didn't know where it saved files. On issue #10 I read that there should be a notification. I use version 1.0.0, but I get no notification.

**Comment by ryonakano** [comment]
Hmm…I've just installed 1.0.0 from AppCenter but can see a notification when recording is finished. Are you on elementary OS Juno, right? Could you check whether you allow Reco to show bubbles from System Settings→Notifications?

**Comment by HansCronau** [comment]
> Are you on elementary OS Juno, right?

Yes. :)

> Could you check whether you allow Reco to show bubbles from System Settings→Notifications?

That's it! I was recording a business meeting, so I had Do Not Disturb on.
Thanks! :)

Thought: Not knowing _where_ the files are saved is a different problem from not knowing _that_ the files are saved, but they are related. Other than the notification (that I missed) there seems to be no feedback that the recording was successfully saved after pressing stop. This was the reason I started looking for the files in the first place. As a user I would already feel more secure knowing that the file was at least saved _somewhere_. :)
Shall I make a separate issue?

**Comment by ryonakano** [comment]
> That's it! I was recording a business meeting, so I had Do Not Disturb on.

Oh I see. Glad to hear the problem was solved :)

> Thought: Not knowing where the files are saved is a different problem from not knowing that the files are saved, but they are related. Other than the notification (that I missed) there seems to be no feedback that the recording was successfully saved after pressing stop. This was the reason I started looking for the files in the first place. As a user I would already feel more secure knowing that the file was at least saved somewhere. :)
Shall I make a separate issue?

Absolutely. If users turn on Do Not Disturb as you did, there's no way for the users to know the recording is done. Yes, could you make another issue for that?

**Comment by ryonakano** [comment]
Never mind, you don't have to create another issue because I changed the title of this issue :+1:

**Comment by HansCronau** [comment]
> Never mind, you don't have to create another issue because I changed the title of this issue 👍

That works too. Thanks for your active response. :)

**Comment by ryonakano** [comment]
![peek 2018-12-21 23-03](https://user-images.githubusercontent.com/26003928/50346152-ca4e8700-0574-11e9-827b-72715b654bbc.gif)

@HansCronau I've created a fix (#16) for this issue. With this fix users can choose where to save files after finishing recording. I think this let users know where files are saved and that the recording is finished successfully.
Is this fix OK with you? If yes, I'll merge the fix to master :relaxed:

**Comment by HansCronau** [comment]
Nice. I think it's an improvement from not knowing that things are saved and where.

To signal _that_ the file has been saved, you could also consider having the stop button play an animation that communicates this.

About the _where_: I expect some users will really like the initial, quick and smooth don't-tell-me-where-to-save-flow. Maybe you could offer both, like browsers do with their downloads? There you can choose to either set(/check) a default folder or have it ask where to save for every download.

**Comment by ryonakano** [comment]
Thank you for your feedback!!

> To signal _that_ the file has been saved, you could also consider having the stop button play an animation that communicates this.

You mean something like this, don't you? https://dribbble.com/shots/3710002-Check-Mark

And absolutely, some people wants previous flow. I've tried adding a switch and a folder chooser in my local branch:

![peek 2018-12-24 21-43](https://user-images.githubusercontent.com/26003928/50399752-155ed900-07c5-11e9-8144-a95cc5a7aa4b.gif)

**Comment by HansCronau** [comment]
Yes, something like that!

Of course that almost doubles the number of settings. At some point it will look better (more minimalistic) to hide the settings in a menu triggered with a small gear icon in the top right.'

**Comment by ryonakano** [comment]
Reopening since telling the finishing of recording in animation is not implemented in that PR

**Comment by ryonakano** [comment]
I'm not sure how I can implement the animation at all…

**Comment by HansCronau** [comment]
That's a bummer. :P
Before diving into animation, maybe you could test the concept first with less effort.
Do you think you could get a similar effect by replacing the red record button with a green checkmark for the duration of a second after a successful save?

**Comment by ryonakano** [comment]
![peek 2019-01-11 20-31](https://user-images.githubusercontent.com/26003928/51031429-e6779e00-15df-11e9-8450-390ed2b847f8.gif)

Yes, something like that…

**Comment by HansCronau** [comment]
Looking nice. Curious to know how completely new users will respond. My first impression is spoiled now. :P
