### ISSUE TITLE
"Info: runtime org.gnome. Platform branch 42 is end-of-life".

### ISSUE THREAD

**Issue by kanansnote** [ryonakano/reco#190]
Hi there. I'd like to know how to deal with [this issue](https://drive.google.com/file/d/105DzHrlQscjweG2YtMC0WloO6U0fHANZ/view?usp=share_link)? Is there anything you need to do? Thanks.

**Comment by ryonakano** [comment]
Hi, thank you for using Reco!

Yes, it is me that need to work on this…the GNOME runtimes get end-of-life after 2 another releases. Recently 44 is released and then 42, the 2 previous release, got EOL. I was completely forgot about this cycle.

Actually I'm already working on this [here](https://github.com/flathub/com.github.ryonakano.reco/tree/release-4.0.1), and going to publish a new release in this weekend. So you should get update in the next week and then this message should disappear.

**Comment by kanansnote** [comment]
Thank you for taking responsibility for resolving this issue 🙏.

**Comment by ryonakano** [comment]
Thank you too for reminding me this issue! :raised_hands:

Note that I published the latest release in the repository but it often takes a few days until it rolls out as an update.
