### ISSUE TITLE
Offer a way to play the recorded file or browse the containing folder after recording

### ISSUE THREAD

**Issue by nekohayo** [ryonakano/reco#238]
## Use case

I don't always keep Nautilus open to the folder where Reco records, and that folder might be buried multiple levels deep within my filesystem. However, there are situations where I need to quickly check (play) a recording or quickly move/upload it somewhere else after recording. For those purposes, it would be very convenient if Reco allowed opening the containing folder with the user's default file manager, and maybe as a bonus allow opening the resulting file directly with the default audio player associated with that mimetype.

## Possible approach

In the main UI window, there could be a small button next to the recording folder widget to open/browse that folder. However, this wouldn't really allow for playback of files, other than through the file manager.

Alternatively (or maybe _also_ !), it might be easier to accomplish by also showing a notification _with two action buttons_ ("Play" and "View containing folder" or something like that).

Regarding the notification idea, I am a little bit confused about the state of this, because #10 and #14 makes it sound like there _used_ to be a notification when recording was successfully ended, but I am definitely not seeing it on version 5.0.0 from flathub running with Wayland GNOME 45.3 on Fedora 39. My guess is that you probably removed the notification feature entirely in favor of the "auto-save to configurable folder" feature, however I think a notification could still be useful today if it provides action buttons for those two actions.

**Comment by ryonakano** [comment]
Hi, thank you for your ideas/issue reports as always! :tada:

Yes, I agree that offering actions after recording would definitely improve UX.

> Regarding the notification idea, I am a little bit confused about the state of this, because #10 and #14 makes it sound like there _used_ to be a notification when recording was successfully ended, but I am definitely not seeing it on version 5.0.0 from flathub running with Wayland GNOME 45.3 on Fedora 39. My guess is that you probably removed the notification feature entirely in favor of the "auto-save to configurable folder" feature, however I think a notification could still be useful today if it provides action buttons for those two actions.

Yes, Reco used to show a notification bubble after recording but it was removed for a while ago in favor of the green check mark (#23). The reason we gave up using a notification is that it won't work if a user turns on Do Not Disturb (e.g. in case of business use like meetings). So, I think it would be better to use in-app notification like toast popup with the two action buttons.
