### ISSUE TITLE
Error while installing packages on elementary OS

### ISSUE THREAD

**Issue by f-imbi** [ryonakano/reco#49]
Extracted data "./boot/System.map-4.15.0-66-generic" can not be copied to "./boot/System.map-4.15.0-66-generic.dpkg-new"
![Bildschirmfoto von 2019-11-01 10-14-12@2x](https://user-images.githubusercontent.com/38214242/68014814-cf9a5900-fc90-11e9-88bc-862778e100d9.png)

**Comment by ryonakano** [comment]
Judging from the error message, I guess you have a corrupted download with Linux kernel or something like that, which is not scope for Reco.
