### ISSUE TITLE
Only WAV or AAC gives a stereo file

### ISSUE THREAD

**Issue by stevebrodie** [ryonakano/reco#66]
When I record from my computer only using AAC or WAV I get a stereo file. Using any other format, and still recording just the computer, I get a mono file.  Is this expected behaviour or a bug?
A nice app though, thank you!

Steve

**Comment by ryonakano** [comment]
Hi, thank you for your report! I guess the recorded file should be always stereo. I always get a stereo file whether I chose either format.

What kind of microphone are you using? If possible, could you share the recorded files (both the stereo one and the mono one)?

**Comment by stevebrodie** [comment]
Hi, Thank you for your reply.  I would certainly expect any files using the computer as the source to be stereo, maybe not the microphone as that is usually a mono source.  Regardless I would expect that the behaviour should be consistent across all the outputs formats. (I hope that doesn't sound rude - it's your app after all, maybe you disagree! That's just my view as an end user).
Here is a link to some recordings as requested: https://app.box.com/s/041h5lec8303oq2mp42n4m6javxj98jt
I am just using the internal microphone on a Thinkpad T410 (which is terrible quality I'm afraid).
I haven't done an exhaustive test yet but the behaviour seems to be the same whether I select 'computer', 'microphone' or both; WAV and AAC produces a stereo file, everything else mono.

Best wishes, Steve

**Comment by ryonakano** [comment]
Hi, sorry for my delayed reply. I listened to your recordings and only wav and aac files are in stereo, indeed. I thought I still couldn't able to reproduce the issue with my microphone, but when I tried recording internal sounds I was able to reproduce it finally. Thank you for your investigation! (And I also found my microphone only gives a **mono** file regardless of a file format―maybe because my microphone was cheap…)

**Comment by stevebrodie** [comment]
Hi,  Glad you could reproduce this! 😀  My view, and I have been an audio pro for over 20 years, is that a mono file from the microphone is acceptable and probably even desireable as the microphone is unlikely to be stereo.
I would expect the recordings of the system, or computer, audio to be stereo though.
Let me know if I can help anymore at all, although sadly I'm not a developer; I'm just taking my first steps in trying to learn.
Thank you and good luck!

**Comment by ryonakano** [comment]
Hi, I've just created a PR that should fix this issue (#68). I have a question: should the number of channels be always 2 (dual), or be choosable by users?

**Comment by stevebrodie** [comment]
Hi, I think it would be nice if you could choose, with the default setting being stereo.  That way if you know that what you're recording has no stereo information, or if you just want a smaller file size you can choose to have a mono recording.

**Comment by ryonakano** [comment]
My PR should fix the issue, but I found one weird point: AAC does not give me the correct stereo file―both in the latest version and in my PR.

I recorded the audio of the following demo video for testing if the app records in stereo as expected:

https://www.youtube.com/watch?v=6TWJaFD6R2s

I tried recording in each format, and the other formats are OK, but AAC gives me a strange recording.

I uploaded recordings in AAC and MP3 to Google Drive, I hope you would listen to them:

https://drive.google.com/drive/folders/1gZfNxCuBTa-QQa6hH3EV8dL6ELUEZCyo?usp=sharing

Do you also see this issue on your side using the latest version? If you can reproduce this issue, I'll put
